server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: secret
            redirect-uri: http://localhost:8080/login/oauth2/code/login-client
            scope: openid
          person-client:
            provider: spring
            client-id: person-client
            client-secret: s3cr3t
            redirect-uri: http://localhost:8080/person-flow/address
            scope: person:search, person:metrics
        provider:
          spring:
            issuer-uri: http://auth-server:9000

oauth2:
  resource:
    services:
      person-service:
        uri: http://localhost:8090/person-service/address
